"""LLM-based mock hotel offer generation.

Each hotel option is generated by an LLM rather than pulled from a static
lookup table, so names and prices actually reflect the destination instead
of repeating the same fixed entries. Options are generated one at a time,
each call told what's already been suggested so the results don't repeat.
"""

import json
import os

from dotenv import load_dotenv
from openai import AsyncOpenAI
from pydantic import BaseModel

load_dotenv()

_MODEL = os.environ.get('OPENAI_MODEL', 'gpt-4o-mini')

_OFFER_SYSTEM_PROMPT = (
    'You are a hotel search agent. Given a destination, date range, and '
    'guest count, suggest ONE plausible hotel: a realistic-sounding name for '
    'the destination and a believable average nightly rate in USD. Do not '
    'repeat any hotel already listed as excluded.'
)

_OFFER_RESPONSE_SCHEMA = {
    'name': 'hotel_offer',
    'strict': True,
    'schema': {
        'type': 'object',
        'properties': {
            'hotel_name': {'type': 'string'},
            'price_per_night_usd': {'type': 'number'},
        },
        'required': ['hotel_name', 'price_per_night_usd'],
        'additionalProperties': False,
    },
}


class HotelOffer(BaseModel):
    hotel_name: str
    price_per_night_usd: float


async def generate_hotel_offer(
    destination: str,
    checkin: str,
    checkout: str,
    guests: int,
    exclude: list[str] | None = None,
) -> HotelOffer:
    """Uses an LLM to invent one plausible hotel option for this trip."""
    user_prompt = (
        f'Destination: {destination}\n'
        f'Check-in: {checkin}\n'
        f'Check-out: {checkout}\n'
        f'Guests: {guests}'
    )
    if exclude:
        user_prompt += f'\nAlready suggested, exclude: {", ".join(exclude)}'

    client = AsyncOpenAI()
    completion = await client.chat.completions.create(
        model=_MODEL,
        messages=[
            {'role': 'system', 'content': _OFFER_SYSTEM_PROMPT},
            {'role': 'user', 'content': user_prompt},
        ],
        response_format={
            'type': 'json_schema',
            'json_schema': _OFFER_RESPONSE_SCHEMA,
        },
    )
    data = json.loads(completion.choices[0].message.content)
    return HotelOffer(**data)
